#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

read -r -d '' report << EOM
---------------------------------
Audio Files: $(ls -F $parentdir/media/audio | wc -l)
Video Files: $(ls -F $parentdir/media/video | wc -l)
Image Files: $(ls -F $parentdir/media/images | wc -l)
YouTube Files: $(ls -F $parentdir/media/youtube | wc -l)
---------------------------------
Host Name: $HOSTNAME
---------------------------------
Date: $(date)
---------------------------------
CPU Usage: $cpuusage
---------------------------------
Disk Usage: $diskusage
---------------------------------
Memory Usage: $memoryusage
---------------------------------
Temperature: $temperature
---------------------------------
Uptime: $uptime
---------------------------------
Local IP: $localip
---------------------------------
Public IP: $publicip
---------------------------------
EOM

{ echo Subject: Report - $HOSTNAME ; echo "$report" ; } | ssmtp emailaddress