#!/bin/bash

configure_service () {
 sudo sed -i -e "s/ip/$ip/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/username/$username/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/password/$password/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/port/$reverseport/g" /etc/systemd/system/tunnel.service
}

echo configuring tunnel service
configure_service