#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

create_service () {
sudo bash -c "cat > /etc/systemd/system/tunnel.service" << EOL
[Unit]
Description=tunnel service
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do sshpass -p $server_pass ssh -p 22 -t -t -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -o ServerAliveCountMax=5 -o ServerAliveInterval=60 -o LogLevel=ERROR $server_user@$server_ip -R $reverse_port:127.0.0.1:22 ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl start tunnel.service
sudo systemctl enable tunnel.service > /dev/null 2>&1
}

echo creating tunnel service
create_service