#!/bin/bash

create_service () {
sudo bash -c 'cat > /etc/systemd/system/tunnel.service' << 'EOL'
[Unit]
Description=tunnel service
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do sshpass -p password ssh -p 22 -t -t -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -o ServerAliveCountMax=5 -o ServerAliveInterval=60 -o LogLevel=ERROR username@ip -R port:127.0.0.1:22 ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

create_service