#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo =============================================================================================
echo - This will enable a tunnel connection to your raspberry pi using an ssh server.
echo - You will be asked to provide the ssh server username/password/ip and reverse port.
echo - The minimum setting on the ssh server is to enable GatewayPorts in /etc/ssh/sshd_config.
echo - You can then connect to this raspberry pi through the tunnel created using your ssh server.
echo =============================================================================================
read -p "press enter to continue"

echo ssh server ip: ; read server_ip ; export server_ip
echo ssh server username: ; read server_user ; export server_user
echo ssh server password: ; read server_pass ; export server_pass
echo ssh server reverse port: ; read reverse_port ; export reverse_port

sed -i -e "s/server_ip=.*/server_ip=$server_ip/" $parentdir/operations/variables
sed -i -e "s/server_user=.*/server_user=$server_user/" $parentdir/operations/variables
sed -i -e "s/server_pass=.*/server_pass=$server_pass/" $parentdir/operations/variables
sed -i -e "s/reverse_port=.*/reverse_port=$reverse_port/" $parentdir/operations/variables

install () {
 if test -f "/etc/systemd/system/tunnel.service" ; then
  $currentdir/function_remove_service
  $currentdir/function_create_service
 else
  $currentdir/function_install_sshpass
  $currentdir/function_create_service
 fi
}

install