#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$currentdir/../operations/variables"

service_video ()
{
sudo bash -c "cat > /etc/systemd/system/video.service" << EOL
[Unit]
Description=video service
After=network.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/cvlc --no-osd --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=wsize --height=hsize videourl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_video
