#!/bin/bash

# variables
parentdir=$(dirname $(dirname $(readlink -fm $0)))

service_youtube ()
{
sudo bash -c "cat > /etc/systemd/system/youtube.service" << EOL
[Unit]
Description=youtube service
After=network.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/cvlc --no-osd --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=wsize --height=hsize --loop $parentdir/media/youtube/"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_youtube