#!/bin/bash

function_stop ()
{
 for service in audio video images youtube browser logo
 do
  sudo systemctl is-active --quiet $service.service
  sudo systemctl stop $service.service
  sudo systemctl disable $service.service  > /dev/null 2>&1
  sudo rm /etc/systemd/system/$service.service
  echo stopping $service
 done
 exit 0
}

function_stop
