#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$currentdir/../operations/variables"

configure_olivetin () {
sudo mv /etc/OliveTin/config.yaml /etc/OliveTin/backup_$(date +'%d_%m_%Y_%I_%M').yaml
sudo bash -c "cat > /etc/OliveTin/config.yaml" << EOL
ListenAddressSingleHTTPFrontend: 0.0.0.0:1337
checkForUpdates: true
showNewVersions: true
hideNavigation: false
logLevel: "INFO"

actions:
- title: Show Logo
  shell: $workingdir/signage_logo
  icon: "&#129703"

- title: Play Video
  icon: "&#128250"
  shell: echo {{ videolink }} | {{ localorstream }}
  arguments:

   - name: videolink
     title: Video Link
     type: very_dangerous_raw_string
     default: $videourl

   - name: localorstream
     title: Local or Stream
     choices:
      - title: Local
        value: $workingdir/signage_video_local

      - title: Stream
        value: $workingdir/signage_video_stream

- title: Play Music
  shell: $workingdir/signage_audio
  icon: "&#128265"

- title: Image Slideshow
  shell: $workingdir/signage_images
  icon: "&#128247"

- title: YouTube Video
  icon: "&#128249"
  shell: echo {{ youtubelink }} | {{ streamordownload }}
  arguments:

   - name: youtubelink
     title: YouTube Link
     type: very_dangerous_raw_string
     default: $youtubeurl

   - name: streamordownload
     title: Stream or Download
     choices:
      - title: Stream
        value: $workingdir/signage_youtube_stream

      - title: Download & Play
        value: $workingdir/signage_youtube_download

- title: Show Website
  shell: echo {{ website }} | $workingdir/signage_browser
  icon: "&#127758"
  arguments:
   - name: website
     title: Website Address
     type: ascii_identifier
     default: $websiteurl

- title: Stop Signage Services
  shell: $workingdir/signage_stop
  icon: "&#9211"
EOL
}

remove_olivetin () {
 sudo dpkg -P olivetin > /dev/null 2>&1
}

install_olivetin () {
 wget $olivetinurl/$olivetindeb > /dev/null 2>&1
 sudo dpkg -i $olivetindeb > /dev/null 2>&1
 rm $olivetindeb
}

start_olivetin () {
 sudo systemctl start OliveTin.service
 sudo systemctl enable OliveTin.service > /dev/null 2>&1
}

install () {
if test -f "/etc/systemd/system/OliveTin.service" ; then
 $(remove_olivetin)
 $(install_olivetin)
 $(configure_olivetin)
 $(start_olivetin)
else
 $(install_olivetin)
 $(configure_olivetin)
 $(start_olivetin)
fi
}

install
