#!/bin/bash

# variables
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$DIR/../operations/variables"

service_audio ()
{
sudo bash -c "cat > /etc/systemd/system/audio.service" << EOL
[Unit]
Description=audio service
After=network.target

[Service]
ExecStart=/bin/bash -c "mpg123 --shuffle $workingdir/media/audio/*"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_audio
