#!/bin/bash

echo ===============================================================================================
echo to allow outgoing emails from your gmail account perform the following steps before continuing
echo 1. visit https://myaccount.google.com/lesssecureapps to allow less secure apps
echo 2. visit https://accounts.google.com/DisplayUnlockCaptcha to allow access to your email account
echo ===============================================================================================
read -p "press enter to continue"

echo gmail username: ; read gmailusername
echo gmail password: ; read gmailpassword

install_ssmtp () {
sudo apt install -y ssmtp > /dev/null 2>&1
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailusername" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

cpumonitor () {
sudo bash -c 'cat > /etc/systemd/system/cpumonitor.service' << 'EOL'
[Unit]
Description=cpu monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(top -b -n1 | grep Cpu | awk '{print $2 + $4}' | awk '{print int($1+0.5)}') -gt 90 ]; then { echo Subject: CPU Alert - $HOSTNAME; echo CPU Usage on $HOSTNAME is $(top -b -n1 | grep Cpu | awk '{print $2 + $4}' | awk '{print int($1+0.5)}')%; } | ssmtp $emailaddress; fi; sleep 3600; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

echo installing ssmtp ; install_ssmtp
echo configuring ssmtp ; configure_ssmtp
