#!/bin/bash

# variables
parentdir=$(dirname $(dirname $(readlink -fm $0)))

remove_filebrowser_service () {
 sudo systemctl stop filebrowser.service
 sudo systemctl disable filebrowser.service > /dev/null 2>&1
 sudo rm -f /etc/systemd/system/filebrowser.service
 sudo systemctl daemon-reload
}

install_filebrowser () {
 curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash > /dev/null 2>&1
}

create_filebrowser_service () {
sudo bash -c "cat > /etc/systemd/system/filebrowser.service" << EOL
[Unit]
Description=filebrowser service
After=network.target

[Service]
ExecStart=/bin/bash -c "filebrowser config set --auth.method=noauth ; filebrowser -r $parentdir/media/ -a 0.0.0.0"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

start_filebrowser_service () {
sudo systemctl daemon-reload
sudo systemctl start filebrowser.service
sudo systemctl enable filebrowser.service > /dev/null 2>&1
}

install () {
if test -f "/etc/systemd/system/filebrowser.service" ; then
 $(remove_filebrowser_service)
 $(install_filebrowser)
 $(create_filebrowser_service)
 $(start_filebrowser_service)
else
 $(install_filebrowser)
 $(create_filebrowser_service)
 $(start_filebrowser_service)
fi
}

install