#!/bin/bash

service_logo ()
{
sudo bash -c 'cat > /etc/systemd/system/logo.service' << 'EOL'
[Unit]
Description=logo service
After=network.target

[Service]
ExecStart=/usr/bin/fim -q /home/pi/digitalsignage/media/logo/logo.png > /dev/null 2>&1 &
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_logo
