#!/bin/bash

service_browser ()
{
sudo bash -c 'cat > /etc/systemd/system/browser.service' << 'EOL'
[Unit]
Description=browser service
After=network.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/chromium-browser -no-sandbox --enable-features=OverlayScrollbar --window-size=wsize,hsize --start-fullscreen --kiosk --incognito --noerrdialogs --no-first-run --fast --fast-start --disable-infobars websiteurl -- -nocursor"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_browser
