#!/bin/bash

browser_service ()
{
sudo bash -c 'cat > /etc/systemd/system/browser.service' << 'EOL'
[Unit]
Description=browser service
After=network.target

[Service]
ExecStart=/bin/bash -c "sudo xinit /usr/bin/midori -e Fullscreen -a weburl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

echo creating browser service
browser_service
