#!/bin/bash

service_youtube ()
{
sudo bash -c 'cat > /etc/systemd/system/youtube.service' << 'EOL'
[Unit]
Description=youtube service
After=network.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/vlc --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=$(fbset -s | awk '/geometry/ { print $2 }') --height=$(fbset -s | awk '/geometry/ { print $3 }') youtubeurl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_youtube
