#!/bin/bash

service_browser ()
{
sudo bash -c 'cat > /etc/systemd/system/browser.service' << 'EOL'
[Unit]
Description=browser service
After=network.target

[Service]
ExecStart=/bin/bash -c "sudo xinit /usr/bin/midori -e Fullscreen -a http://websiteurl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_browser
