#!/bin/bash

service_browser ()
{
sudo bash -c 'cat > /etc/systemd/system/browser.service' << 'EOL'
[Unit]
Description=browser service
After=network.target

[Service]
ExecStart=/bin/bash -c "sudo xinit /usr/bin/midori -e Fullscreen -a weburl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

echo creating browser service
service_browser

echo creating browser directory
sudo mkdir -p /root/.config/midori

echo creating browser configuration
sudo bash -c "cat >> /root/.config/midori/config" << EOL
[settings]
last-window-width=$(fbset -s | awk '/geometry/ { print $2 }')
last-window-height=$(fbset -s | awk '/geometry/ { print $3 }')
EOL
