#!/bin/bash

service_youtube ()
{
sudo bash -c 'cat > /etc/systemd/system/youtube.service' << 'EOL'
[Unit]
Description=youtube service
After=network.target

[Service]
User=pi
ExecStart=/bin/bash -c "xinit /usr/bin/cvlc --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=wsize --height=hsize youtubeurl"
Restart=always
Environment=DISPLAY=:0

[Install]
WantedBy=multi-user.target
EOL
}

service_youtube
