#!/bin/bash

service_audio ()
{
sudo bash -c 'cat > /etc/systemd/system/audio.service' << 'EOL'
[Unit]
Description=audio service
After=network.target

[Service]
ExecStart=/bin/bash -c "while true ; do for audio in $(ls /home/pi/media/audio/* | shuf); do mpg123 $audio; done; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_audio
