#!/bin/bash

stop_service ()
{
 for service in audio video images stream youtube browser logo
 do
  sudo systemctl is-active --quiet $service.service &&
  sudo systemctl stop $service.service &&
  sudo systemctl disable $service.service  > /dev/null 2>&1 &&
  sudo rm /etc/systemd/system/$service.service &&
  echo stop $service
 done
}

echo stop service ; stop_service
