#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo stopping service
$currentdir/functions/function_stop

echo clearing framebuffer
$currentdir/functions/function_framebuffer

echo creating video service
$currentdir/functions/function_video

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/video.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/video.service

echo reloading services
$currentdir/functions/function_reload

echo starting video service
sudo systemctl start video.service

echo enabling video service
sudo systemctl enable video.service > /dev/null 2>&1
