#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo youtube video you want to display: ; read youtubeurl

echo removing previous video
rm -f $currentdir/media/youtube/*

echo downloading youtube video
youtube-dl -o $currentdir/media/youtube/video1.mp4 $youtubeurl

echo stopping service
$currentdir/signage/function_stop

echo clearing framebuffer
$currentdir/signage/function_framebuffer

echo creating youtube service
$currentdir/signage/function_youtube_download

echo reloading services
$currentdir/signage/function_reload

echo starting youtube service
sudo systemctl start youtube.service

echo enabling youtube service
sudo systemctl enable youtube.service > /dev/null 2>&1