#!/bin/bash

source variables

echo youtube video you want to display: ; read youtubeurl

echo stopping service
$workingdir/functions/function_stop

echo clearing framebuffer
$workingdir/functions/function_framebuffer

echo creating youtube service
$workingdir/functions/function_youtube_stream

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/youtube.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/youtube.service

echo configuring youtube url
sudo sed -i -e "s|youtubeurl|$youtubeurl|g" /etc/systemd/system/youtube.service

echo reloading services
$workingdir/functions/function_reload

echo starting youtube service
sudo systemctl start youtube.service

echo enabling youtube service
sudo systemctl enable youtube.service > /dev/null 2>&1
