#!/bin/bash

echo stopping service
/home/pi/digitalsignage/functions/function_stop

echo clearing framebuffer
/home/pi/digitalsignage/functions/function_framebuffer

echo creating images service
/home/pi/digitalsignage/functions/function_images

echo reloading services
/home/pi/digitalsignage/functions/function_reload

echo starting images service
sudo systemctl start images.service

echo enabling images service
sudo systemctl enable images.service > /dev/null 2>&1
