#!/bin/bash

echo stopping service
bash ./functions/function_stop

echo clearing framebuffer
bash ./functions/function_framebuffer

echo creating logo service
bash ./functions/function_logo

echo reloading services
bash ./functions/function_reload

echo starting logo service
sudo systemctl start logo.service

echo enabling logo service
sudo systemctl enable logo.service > /dev/null 2>&1
