#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo stopping service
$currentdir/signage/function_stop

echo clearing framebuffer
$currentdir/signage/function_framebuffer

echo creating video service
$currentdir/signage/function_video_local

echo reloading services
$currentdir/signage/function_reload

echo starting video service
sudo systemctl start video.service

echo enabling video service
sudo systemctl enable video.service > /dev/null 2>&1