#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo video you want to display: ; read videourl

echo configuring video url
sed -i -e "s/videourl=.*/videourl=$videourl/" $currentdir/operations/variables

echo stopping service
$currentdir/signage/function_stop

echo clearing framebuffer
$currentdir/signage/function_framebuffer

echo creating video service
$currentdir/signage/function_video_stream

echo reloading services
$currentdir/signage/function_reload

echo starting video service
sudo systemctl start video.service

echo enabling video service
sudo systemctl enable video.service > /dev/null 2>&1