#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo stopping service
$currentdir/functions/function_stop

echo clearing framebuffer
$currentdir/functions/function_framebuffer

echo reloading services
$currentdir/functions/function_reload
