#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo youtube video you want to display: ; read youtubeurl

echo downloading youtube video
youtube-dl -o $DIR/media/video/video1.mp4 $youtubeurl

echo stopping service
$DIR/functions/function_stop

echo clearing framebuffer
$DIR/functions/function_framebuffer

echo creating video service
$DIR/functions/function_youtube_local

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/youtube.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/youtube.service

echo reloading services
$DIR/functions/function_reload

echo starting video service
sudo systemctl start youtube.service

echo enabling video service
sudo systemctl enable youtube.service > /dev/null 2>&1
