#!/bin/bash

echo youtube video you want to display: ; read youtubeurl

echo stopping service
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/function_service_stop)

echo clearing framebuffer
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/function_service_framebuffer)

echo creating youtube service
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/function_service_youtube)

echo configuring youtube url
sudo sed -i -e "s|youtubeurl|$youtubeurl|g" /etc/systemd/system/youtube.service

echo reloading services
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/function_service_reload)

echo starting youtube service
sudo systemctl start youtube.service

echo enabling youtube service
sudo systemctl enable youtube.service > /dev/null 2>&1
