#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo stopping service
$currentdir/functions/function_stop

echo clearing framebuffer
$currentdir/functions/function_framebuffer

echo creating images service
$currentdir/functions/function_images

echo reloading services
$currentdir/functions/function_reload

echo starting images service
sudo systemctl start images.service

echo enabling images service
sudo systemctl enable images.service > /dev/null 2>&1
