#!/bin/bash

echo stopping service
bash <(wget -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/functions/function_stop)

echo clearing framebuffer
bash <(wget -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/functions/function_framebuffer)

echo creating logo service
bash <(wget -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/functions/function_logo)

echo reloading services
bash <(wget -qO- https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/functions/function_reload)

echo removing existing logo
rm -rf /home/pi/media/logo/*

echo downloading logo
wget https://raw.githubusercontent.com/aristosv/BeatBox-Digital-Signage/main/media/logo/logo.png -P /home/pi/media/logo > /dev/null 2>&1

echo starting logo service
sudo systemctl start logo.service

echo enabling logo service
sudo systemctl enable logo.service > /dev/null 2>&1
