#!/bin/bash

echo youtube video you want to display: ; read youtubeurl

echo removing existing video
rm -rf /home/pi/media/youtube/*

echo downloading $youtubeurl
cd /home/pi/media/youtube ; youtube-dl --restrict-filenames $youtubeurl

echo stopping service
bash ./functions/function_stop

echo clearing framebuffer
bash ./functions/function_framebuffer

echo creating video service
bash ./functions/function_youtube_local

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/youtube.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/youtube.service

echo reloading services
bash ./functions/function_reload

echo starting video service
sudo systemctl start youtube.service

echo enabling video service
sudo systemctl enable youtube.service > /dev/null 2>&1
