#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo website you want to display: ; read websiteurl

echo stopping service
$currentdir/signage/function_stop

echo clearing framebuffer
$currentdir/signage/function_framebuffer

echo creating browser service
$currentdir/signage/function_browser

echo configuring website
sudo sed -i -e "s|websiteurl|$websiteurl|g" /etc/systemd/system/browser.service

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/browser.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/browser.service

echo reloading services
$currentdir/signage/function_reload

echo starting browser service
sudo systemctl start browser.service

echo enabling browser service
sudo systemctl enable browser.service > /dev/null 2>&1