#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo youtube video you want to display: ; read youtubeurl

echo removing previous video
rm -f $currentdir/media/youtube/*

echo downloading youtube video
youtube-dl -o $currentdir/media/youtube/video1.mp4 $youtubeurl

echo stopping service
$currentdir/functions/function_stop

echo clearing framebuffer
$currentdir/functions/function_framebuffer

echo creating youtube service
$currentdir/functions/function_youtube_download

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/youtube.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/youtube.service

echo reloading services
$currentdir/functions/function_reload

echo starting youtube service
sudo systemctl start youtube.service

echo enabling youtube service
sudo systemctl enable youtube.service > /dev/null 2>&1
