#!/bin/bash

echo website you want to display: ; read websiteurl

echo stopping service
bash ./functions/function_stop

echo clearing framebuffer
bash ./function_framebuffer

echo creating browser service
bash ./functions/function_browser

echo configuring website
sudo sed -i -e "s|websiteurl|$websiteurl|g" /etc/systemd/system/browser.service

echo configuring width size
sudo sed -i -e "s|wsize|$(fbset -s | awk '/geometry/ { print $2 }')|g" /etc/systemd/system/browser.service

echo configuring height size
sudo sed -i -e "s|hsize|$(fbset -s | awk '/geometry/ { print $3 }')|g" /etc/systemd/system/browser.service

echo reloading services
bash ./functions/function_reload

echo starting browser service
sudo systemctl start browser.service

echo enabling browser service
sudo systemctl enable browser.service > /dev/null 2>&1
