#!/bin/bash

echo stopping service
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox2/main/function_service_stop)

echo clearing framebuffer
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox2/main/function_service_framebuffer)

echo creating browser service
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox2/main/function_service_browser)

echo reloading services
bash <(wget --no-check-certificate -qO- https://raw.githubusercontent.com/aristosv/BeatBox2/main/function_service_reload)

echo starting browser service
sudo systemctl start browser.service

echo enabling browser service
sudo systemctl enable browser.service
