#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo creating cpumonitor
$currentdir/function_cpumonitor

echo creating diskmonitor
$currentdir/function_diskmonitor

echo creating memorymonitor
$currentdir/function_memorymonitor

echo creating temperaturemonitor
$currentdir/function_temperaturemonitor

echo reloading services
$currentdir/functions/function_reload

enable_monitoring ()
{
 for service in cpumonitor diskmonitor memorymonitor temperaturemonitor
 do
  sudo sed -i -e "s|emailaddress|$emailaddress|g" /etc/systemd/system/$service.service
  sudo systemctl start $service.service
  sudo systemctl enable $service.service  > /dev/null 2>&1
 done
 exit 0
}

enable_monitoring
