#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$currentdir/../operations/variables"

echo =============================================================================================
echo This will enable email alerts for cpu/disk/memory/temperature usage.
echo You will be asked to provide the username and password of a gmail account.
echo Perform the following steps to enable access to a gmail account before proceeding.
echo ---------------------------------------------------------------------------------------------
echo 1. Visit https://myaccount.google.com/lesssecureapps to enable less secure app access.
echo 2. Visit https://accounts.google.com/DisplayUnlockCaptcha to allow access to a gmail account.
echo =============================================================================================
read -p "press enter to continue"

echo gmail address: ; read gmailaddress ; export gmailaddress
echo gmail password: ; read gmailpassword ; export gmailpassword

install_ssmtp () {
 sudo apt install -y ssmtp > /dev/null 2>&1
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailaddress" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

create_services () {
$currentdir/function_cpumonitor
$currentdir/function_diskmonitor
$currentdir/function_memorymonitor
$currentdir/function_temperaturemonitor
$workingdir/functions/function_reload
}

remove_services () {
 sudo systemctl stop $service.service
 sudo systemctl disable $service.service
 sudo rm -f /etc/systemd/system/$service.service
}

enable_services () {
 sudo sed -i -e "s|emailaddress|$gmailaddress|g" /etc/systemd/system/$service.service
 sudo systemctl start $service.service
 sudo systemctl enable $service.service
}

install () {
for service in cpumonitor diskmonitor memorymonitor temperaturemonitor
 do
  if test -f "/etc/systemd/system/$service.service" ; then
   $(remove_services)
   $(create_services)
   $(enable_services)
  else
   $(install_ssmtp)
   $(configure_ssmtp)
   $(create_services)
   $(enable_services)
  fi
 done
}

install
