#!/bin/bash

# variables
parentdir=$(dirname $(dirname $(readlink -fm $0)))

configure_service () {
 sudo sed -i -e "s|parentdir|$parentdir|g" /etc/systemd/system/monitor.service
}

echo configuring monitoring service
configure_service