#!/bin/bash

echo This will setup ssmtp on your raspberry pi and enable email alerts for cpu/disk/memory/temperature usage

echo gmail address: ; read gmailaddress ; export gmailaddress
echo gmail password: ; read gmailpassword ; export gmailpassword

install_ssmtp () {
 sudo apt install -y ssmtp
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailaddress" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

install_ssmtp
configure_ssmtp
