#!/bin/bash

remove_services () {
for service in cpumonitor diskmonitor memorymonitor temperaturemonitor
 do
  sudo systemctl stop $service.service
  sudo systemctl disable $service.service
  sudo rm -f /etc/systemd/system/$service.service
 done
}

remove_services