#!/bin/bash

echo gmail username: ; read gmailusername
echo gmail password: ; read gmailpassword
echo email address to send alerts: ; read emailaddress

install_ssmtp () {
 sudo apt install -y ssmtp
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailusername" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

install_ssmtp
configure_ssmtp
