#!/bin/bash

temperaturemonitor () {
sudo bash -c 'cat > /etc/systemd/system/temperaturemonitor.service' << 'EOL'
[Unit]
Description=temperature monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(sudo /usr/bin/vcgencmd measure_temp | sed -e 's/temp=//' | sed -e "s/[.].*//") -gt 1 ]; then { echo Subject: Temperature Alert - $HOSTNAME; echo Temperature on $HOSTNAME is $(sudo /usr/bin/vcgencmd measure_temp | sed -e 's/temp=//' | sed -e "s/[.].*//"); } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

temperaturemonitor
