#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$currentdir/../operations/variables"

configure_service () {
 sudo sed -i -e "s|threshold|1|g" /etc/systemd/system/monitor.service
 sudo sed -i -e "s|workingdir|$workingdir|g" /etc/systemd/system/monitor.service
 sudo sed -i -e "s|emailaddress|$gmailaddress|g" /etc/systemd/system/monitor.service
}

configure_service