#!/bin/bash

function_service () {
sudo bash -c 'cat > /etc/systemd/system/monitor.service' << 'EOL'
[Unit]
Description=monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true ; do workingdir/monitoring/function_monitor ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

echo creating service
function_service