#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

echo ---------------------------------
echo "Audio Files: $(ls -F $parentdir/media/audio | wc -l)"
echo "Video Files: $(ls -F $parentdir/media/video | wc -l)"
echo "Image Files: $(ls -F $parentdir/media/images | wc -l)"
echo "YouTube Files: $(ls -F $parentdir/media/youtube | wc -l)"
echo ---------------------------------
echo "Host Name: $HOSTNAME"
echo ---------------------------------
echo "Date: $(date)"
echo ---------------------------------
echo "CPU Usage: $cpuusage
echo ---------------------------------
echo "Disk Usage: $diskusage
echo ---------------------------------
echo "Memory Usage: $memoryusage
echo ---------------------------------
echo "Temperature: $temperature
echo ---------------------------------
echo "Uptime: $uptime
echo ---------------------------------
echo "Local IP: $localip
echo ---------------------------------
echo "Public IP: $publicip
echo ---------------------------------