#!/bin/bash

create_services () {
sudo bash -c 'cat > /etc/systemd/system/cpumonitor.service' << 'EOL'
[Unit]
Description=cpu monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(top -b -n1 | grep Cpu | awk '{print $2 + $4}' | awk '{print int($1+0.5)}') -gt threshold ]; then { echo Subject: CPU Alert - $HOSTNAME; echo CPU Usage on $HOSTNAME is $(top -b -n1 | grep Cpu | awk '{print $2 + $4}' | awk '{print int($1+0.5)}')%; } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo bash -c 'cat > /etc/systemd/system/diskmonitor.service' << 'EOL'
[Unit]
Description=disk monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(df --output=pcent / | sed '1d;s/^ //;s/%//') -gt threshold ]; then { echo Subject: Disk Alert - $HOSTNAME; echo Disk Usage on $HOSTNAME is $(df --output=pcent / | sed '1d;s/^ //;s/%//')%; } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo bash -c 'cat > /etc/systemd/system/memorymonitor.service' << 'EOL'
[Unit]
Description=memory monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(free | grep Mem | awk '{print $3/$2 * 100.0}' | awk '{print int($1+0.5)}') -gt threshold ]; then { echo Subject: Memory Alert - $HOSTNAME; echo Memory Usage on $HOSTNAME is $(free | grep Mem | awk '{print $3/$2 * 100.0}' | awk '{print int($1+0.5)}')%; } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo bash -c 'cat > /etc/systemd/system/temperaturemonitor.service' << 'EOL'
[Unit]
Description=temperature monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(sudo /usr/bin/vcgencmd measure_temp | sed -e 's/temp=//' | sed -e "s/[.].*//") -gt threshold ]; then { echo Subject: Temperature Alert - $HOSTNAME; echo Temperature on $HOSTNAME is $(sudo /usr/bin/vcgencmd measure_temp | sed -e 's/temp=//' | sed -e "s/[.].*//")°C; } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

create_services