#!/bin/bash

diskmonitor () {
sudo bash -c 'cat > /etc/systemd/system/diskmonitor.service' << 'EOL'
[Unit]
Description=disk monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do if [ $(df --output=pcent / | sed '1d;s/^ //;s/%//') -gt 90 ]; then { echo Subject: Disk Alert - $HOSTNAME; echo Disk Usage on $HOSTNAME is $(df --output=pcent / | sed '1d;s/^ //;s/%//')%; } | ssmtp emailaddress; fi; sleep 60; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

}

diskmonitor
