#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$currentdir/../operations/variables"

echo ==================================================================================
echo This will enable email alerts for cpu/disk/memory/temperature usage.
echo You will be asked to provide the username and password of a gmail account.
echo Perform the following steps to enable access to a gmail account before proceeding.
echo ----------------------------------------------------------------------------------

echo gmail address: ; read gmailaddress ; export gmailaddress
echo gmail password: ; read gmailpassword ; export gmailpassword

install_ssmtp () {
 sudo apt install -y ssmtp
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailaddress" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

echo creating cpumonitor
$currentdir/function_cpumonitor

echo creating diskmonitor
$currentdir/function_diskmonitor

echo creating memorymonitor
$currentdir/function_memorymonitor

echo creating temperaturemonitor
$currentdir/function_temperaturemonitor

echo reloading services
$workingdir/functions/function_reload

enable_monitoring ()
{
 for service in cpumonitor diskmonitor memorymonitor temperaturemonitor
 do
  sudo sed -i -e "s|emailaddress|$gmailaddress|g" /etc/systemd/system/$service.service
  sudo systemctl start $service.service
  sudo systemctl enable $service.service  > /dev/null 2>&1
 done
 exit 0
}

install_ssmtp
configure_ssmtp
enable_monitoring
