#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo =============================================================================================
echo - This will enable email alerts for cpu/disk/memory/temperature usage.
echo - You will be asked to provide the username and password of a gmail account.
echo - Before proceeding perform the following steps to enable access to any gmail account.
echo ---------------------------------------------------------------------------------------------
echo 1. Visit https://myaccount.google.com/lesssecureapps to enable less secure app access.
echo 2. Visit https://accounts.google.com/DisplayUnlockCaptcha to allow access to a gmail account.
echo =============================================================================================
read -p "press enter to continue"

echo gmail address: ; read gmailaddress ; export gmailaddress
echo gmail password: ; read gmailpassword ; export gmailpassword

install () {
 if test -f "/etc/systemd/system/monitor.service" ; then
  $currentdir/function_remove_service
  $currentdir/function_create_service
  $currentdir/function_configure_service
  $currentdir/function_reload
  $currentdir/function_enable_service
 else
  $currentdir/function_install_ssmtp
  $currentdir/function_configure_ssmtp
  $currentdir/function_create_service
  $currentdir/function_configure_service
  $currentdir/function_reload
  $currentdir/function_enable_service
 fi
}

install