#!/bin/bash

currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo gmail username: ; read gmailusername
echo gmail password: ; read gmailpassword
echo email address to send alerts: ; read emailaddress

echo creating cpumonitor
$currentdir/function_cpumonitor

echo creating diskmonitor
$currentdir/function_diskmonitor

echo creating memorymonitor
$currentdir/function_memorymonitor

echo creating temperaturemonitor
$currentdir/function_temperaturemonitor

echo reloading services
sudo systemctl daemon-reload

install_ssmtp () {
 sudo apt install -y ssmpt
}

configure_ssmtp () {
 sudo truncate -s 0 /etc/ssmtp/ssmtp.conf
 echo "AuthUser=$gmailusername" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "AuthPass=$gmailpassword" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
 echo 'UseSTARTTLS=YES' | sudo tee -a /etc/ssmtp/ssmtp.conf > /dev/null
}

enable_monitoring ()
{
 for service in cpumonitor diskmonitor memorymonitor temperaturemonitor
 do
  sudo sed -i -e "s|emailaddress|$emailaddress|g" /etc/systemd/system/$service.service
  sudo systemctl start $service.service
  sudo systemctl enable $service.service  > /dev/null 2>&1
 done
 exit 0
}

enable_monitoring
