#!/bin/bash

echo =============================================================================================
echo - This will enable a tunnel connection to your raspberry pi using an ssh server.
echo - You will be asked to provide the ssh server username/password/ip and reverse port.
echo - You can then connect to this raspberry pi through the tunnel created using your ssh server.
echo =============================================================================================
read -p "press enter to continue"

echo ssh server ip: ; read ip ; export ip
echo ssh server username: ; read user ; export user
echo ssh server password: ; read pass ; export pass
echo ssh server reverse port: ; read reverseport ; export reverseport

create_service () {
sudo bash -c 'cat > /etc/systemd/system/tunnel.service' << 'EOL'
[Unit]
Description=tunnel service
After=network.target

[Service]
ExecStart=/bin/bash -c "while true; do sshpass -p pass ssh -p 22 -t -t -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -o ServerAliveCountMax=5 -o ServerAliveInterval=60 -o LogLevel=ERROR user@ip -R port:127.0.0.1:22 ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

configure_service () {
 sudo sed -i -e "s/ip/$ip/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/user/$username/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/pass/$password/g" /etc/systemd/system/tunnel.service
 sudo sed -i -e "s/port/$reverseport/g" /etc/systemd/system/tunnel.service
}

enable_service () {
 sudo systemctl daemon-reload
 sudo systemctl start tunnel.service
 sudo systemctl enable tunnel.service > /dev/null 2>&1
}

remove_service () {
 sudo systemctl stop tunnel.service
 sudo systemctl disable tunnel.service
 sudo rm -f /etc/systemd/system/tunnel.service
}

install_sshpass () {
 sudo apt install -y sshpass > /dev/null 2>&1
}

install () {
 if test -f "/etc/systemd/system/tunnel.service" ; then
  $(remove_service)
  $(create_service)
  $(configure_service)
  $(enable_service)
 else
  $(install_sshpass)
  $(create_service)
  $(configure_service)
  $(enable_service)
 fi
}

install