#!/bin/bash

{
# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $currentdir/variables

echo setting permissions
chmod +x $currentdir/config_* $workingdir/signage_* $workingdir/functions/function_* $workingdir/monitoring/function_* $workingdir/tunnel/function_*

echo configuring system
$currentdir/config_system

echo installing prerequisites
$currentdir/config_prerequisites

echo installing olivetin
$workingdir/functions/function_olivetin

echo installing filebrowser
$workingdir/functions/function_filebrowser

echo enabling logo
$workingdir/signage_logo

} | sudo tee /var/log/digitalsignage_install_$(date +'%d_%m_%Y_%I_%M').log