#!/bin/bash

{
# variables
installdir=/home/pi/digitalsignage

# installation
echo updating
sudo apt update > /dev/null 2>&1

echo upgrading
sudo apt -y upgrade > /dev/null 2>&1

echo installing xinit
sudo apt install -y xinit > /dev/null 2>&1
sudo sed -i -e 's/console/anybody/g' /etc/X11/Xwrapper.config

echo installing chromium
sudo apt install -y chromium-browser > /dev/null 2>&1

echo installing vlc
sudo apt install -y vlc > /dev/null 2>&1
sudo sed -i 's/geteuid/getppid/' /usr/bin/vlc

echo installing youtube-dl
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl > /dev/null 2>&1
sudo chmod a+rx /usr/local/bin/youtube-dl

echo installing mpg123
sudo apt install -y mpg123 > /dev/null 2>&1

echo installing fim
sudo apt install -y fim > /dev/null 2>&1

echo installing xdotool
sudo apt install -y xdotool > /dev/null 2>&1

echo installing git
sudo apt install -y git > /dev/null 2>&1

echo installing digitalsignage
git clone https://github.com/aristosv/digitalsignage.git $installdir > /dev/null 2>&1
chmod -R +x $installdir/signage_*
chmod -R +x $installdir/functions/function_*

echo installing olivetin
$installdir/functions/function_olivetin

echo installing filebrowser
$installdir/functions/function_filebrowser

# configuration
echo hiding rainbow
sudo sed -i '1 i\disable_splash=1' /boot/config.txt

echo hiding boot icons
sudo sed -i "1 s|$| logo.nologo quiet splash|" /boot/cmdline.txt

echo hiding boot messages
sudo sed -i "1 s|$| quiet splash|" /boot/cmdline.txt

echo disabling login prompt
sudo systemctl disable getty@tty1.service > /dev/null 2>&1

echo removing default pi password warning
sudo rm /etc/profile.d/sshpwd.sh

echo hiding blinking cursor
sudo sed -i "1 s|$| vt.global_cursor_default=0|" /boot/cmdline.txt

echo hiding undervoltage message on boot
sudo sed -i "1 s|$| loglevel=1|" /boot/cmdline.txt

echo hiding undervoltage lightning bolt icon
sudo sed -i '1 i\avoid_warnings=1' /boot/config.txt

echo preventing sleep
echo '*/5 * * * * root export DISPLAY=:0.0 ; sudo xdotool key Ctrl > /dev/null 2>&1 ' | sudo tee -a /etc/cron.d/nosleep > /dev/null

echo hushing login
touch /home/pi/.hushlogin

echo enabling logo
$installdir/signage_logo

echo removing install script
rm -f /home/pi/install

echo restarting
sudo reboot
} | tee /tmp/digitalsignage_install_$(date +'%d_%m_%Y_%I_%M').log
