#!/bin/bash

{
# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $currentdir/variables

echo setting permissions
chmod +x $currentdir/config_* $parentdir/signage_* $parentdir/signage/function_* $parentdir/monitoring/function_* $parentdir/tunnel/function_*

echo configuring system
$currentdir/config_system

echo installing prerequisites
$currentdir/config_prerequisites

echo installing olivetin
$parentdir/functions/function_olivetin

echo installing filebrowser
$parentdir/functions/function_filebrowser

echo enabling logo
$parentdir/signage_logo

} | sudo tee /var/log/digitalsignage_install_$(date +'%d_%m_%Y_%I_%M').log