#!/bin/bash

{
# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo updating digitalsignage
cd $parentdir
git reset --hard > /dev/null 2>&1
git pull origin main > /dev/null 2>&1

echo setting permissions
chmod +x $currentdir/config_* $parentdir/signage_* $parentdir/signage/function_* $parentdir/monitoring/function_* $parentdir/tunnel/function_*

echo updating olivetin
$parentdir/signage/function_olivetin

echo updating filebrowser
$parentdir/signage/function_filebrowser

} | sudo tee /var/log/digitalsignage_update_$(date +'%d_%m_%Y_%I_%M').log