#!/bin/bash

# variables
installdir=/home/pi/digitalsignage
olivetindeb=OliveTin_2022-01-06_linux_arm64.deb
githubpath=https://github.com/OliveTin/OliveTin/releases/download/2022-01-06

# digitalsignage
echo pulling changes from repository
cd $installdir
git pull origin main

# OliveTin
echo stopping OliveTin service
sudo systemctl stop OliveTin.service

echo backing up OliveTin configuration
sudo mv /etc/OliveTin/config.yaml /etc/OliveTin/backup_$(date +'%d_%m_%Y_%I_%M').yaml

echo removing OliveTin
sudo dpkg -P olivetin

echo installing OliveTin
wget $githubpath/$olivetindeb > /dev/null 2>&1
sudo dpkg -i $olivetindeb > /dev/null 2>&1

echo creating new OliveTin configuration
sudo bash -c 'cat > /etc/OliveTin/config.yaml' << 'EOL'
listenAddressSingleHTTPFrontend: 0.0.0.0:1337
checkForUpdates: false
showNewVersions: false
hideNavigation: false
logLevel: "INFO"

actions:
- title: Show Logo
  shell: /home/pi/digitalsignage/signage_logo
  icon: "&#129703"

- title: Play Video
  shell: /home/pi/digitalsignage/signage_video
  icon: "&#128250"

- title: Play Audio
  shell: /home/pi/digitalsignage/signage_audio
  icon: "&#128265"

- title: Show Images
  shell: /home/pi/digitalsignage/signage_images
  icon: "&#128247"

- title: Show Website
  shell: echo {{ website }} | /home/pi/digitalsignage/signage_browser
  icon: "&#127758"
  arguments:
    - name: website
      title: Website Address
      type: ascii_identifier
      default: apple.com

- title: YouTube - Download Video
  shell: echo {{ youtube }} | /home/pi/digitalsignage/signage_youtube_download
  icon: "&#128253"
  arguments:
    - name: youtube
      title: YouTube Link
      type: very_dangerous_raw_string
      default: https://youtu.be/QC8iQqtG0hg

- title: YouTube - Stream Video
  shell: echo {{ youtube }} | /home/pi/digitalsignage/signage_youtube_stream
  icon: "&#128249"
  arguments:
    - name: youtube
      title: YouTube Link
      type: very_dangerous_raw_string
      default: https://youtu.be/QC8iQqtG0hg

- title: Stop Signage Services
  shell: /home/pi/digitalsignage/signage_stop
  icon: "&#9211"
EOL

echo starting olivetin service
sudo systemctl start OliveTin.service
sudo systemctl enable OliveTin.service > /dev/null 2>&1
rm $olivetindeb
