#!/bin/bash

websiteurl=apple.com
workingdir=/home/pi/digitalsignage
youtubeurl=https://youtu.be/QC8iQqtG0hg
olivetindeb=OliveTin_2022-01-06_linux_arm64.deb
olivetinurl=https://github.com/OliveTin/OliveTin/releases/download/2022-01-06
