#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

create_cronjob () {
sudo bash -c "cat > /etc/cron.d/report" << EOL
@reboot root "$currentdir/function_create_report"
EOL
}

echo creating cron job
create_cronjob