#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function_service_monitor () {
sudo bash -c "cat > /etc/systemd/system/monitor.service" << EOL
[Unit]
Description=monitor service
After=network.target

[Service]
ExecStart=/bin/bash -c "while true ; do $currentdir/function_monitor ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

function_service_report () {
sudo bash -c "cat > /etc/systemd/system/report.service" << EOL
[Unit]
Description=report service
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c "$currentdir/function_report"

[Install]
WantedBy=multi-user.target
EOL
}

start_services () {
for service in monitor report
do
 sudo systemctl start $service.service
 sudo systemctl enable $service.service > /dev/null 2>&1
done
}

echo creating monitoring service
function_service_monitor

echo creating reporting service
function_service_report

echo reloading services
$parentdir/signage/function_reload

echo starting services
start_services