#!/bin/bash

# variables
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# monitor
function_service_monitor () {
sudo bash -c "cat > /etc/systemd/system/monitor.service" << EOL
[Unit]
Description=monitor
After=network.target

[Service]
ExecStart=/bin/bash -c "while true ; do $currentdir/function_monitor ; sleep 60 ; done"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl start monitor.service
sudo systemctl enable monitor.service > /dev/null 2>&1
}

# report
function_service_report () {
sudo bash -c "cat > /etc/systemd/system/report.service" << EOL
[Unit]
Description=report
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c "$currentdir/function_report"
Restart=always

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl start report.service
sudo systemctl enable report.service > /dev/null 2>&1
}

echo creating monitoring service
function_service_monitor

echo creating reporting service
function_service_report