#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

install_ssmtp () {
if ! dpkg -s ssmtp >/dev/null 2>&1; then
 sudo apt install -y ssmtp > /dev/null 2>&1
fi
}

configure_ssmtp () {
sudo rm -f /etc/ssmtp/ssmtp.conf
sudo bash -c "cat > /etc/ssmtp/ssmtp.conf" << EOL
AuthUser=$emailaddress
AuthPass=$emailpassword
mailhub=$mailhub
UseSTARTTLS=YES
EOL
}

echo installing ssmtp
install_ssmtp

echo configuring ssmtp
configure_ssmtp