#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

install_postfix () {
sudo bash -c "echo postfix postfix/mailname string $(hostname --fqdn) | debconf-set-selections" > /dev/null 2>&1
sudo bash -c "echo postfix postfix/main_mailer_type string 'Internet Site' | debconf-set-selections" > /dev/null 2>&1
sudo apt install -y postfix mailutils > /dev/null 2>&1
}

configure_postfix () {
sudo rm -f /etc/postfix/main.cf
sudo bash -c "cat > /etc/postfix/main.cf" << EOL
smtpd_banner = $HOSTNAME ESMTP (Debian/GNU)
biff = no
append_dot_mydomain = no
readme_directory = no
compatibility_level = 2
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_security_level=may
smtp_tls_CApath=/etc/ssl/certs
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = $HOSTNAME.localdomain
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = $HOSTNAME, localhost.localdomain, localhost
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_protocols = all
smtp_sasl_auth_enable = yes
inet_interfaces = 127.0.0.1
smtp_tls_security_level = encrypt
relayhost = $smtpserver
smtp_sasl_security_options = noanonymous
sender_canonical_maps = regexp:/etc/postfix/sender_canonical_maps
smtp_sasl_password_maps = static:$emailaddress:$emailpassword
EOL
sudo rm -f /etc/postfix/sender_canonical_maps
sudo bash -c "echo \"/.+/ $emailaddress\" >> /etc/postfix/sender_canonical_maps"
sudo systemctl restart postfix
}

send_email () {
echo "This is a confirmation that your system can send emails" | mail -s "Confirmation Email" $emailaddress
}

echo installing postfix
install_postfix

echo configuring postfix
configure_postfix

echo sending test email
send_email