#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo ==========================================================================
echo - This will enable email alerts for cpu/disk/memory/temperature usage.
echo - You will be asked to provide smtp/username/password of an email account.
echo ==========================================================================
read -p "press enter to continue"

echo smtp server: ; read smtpserver ; export smtpserver
echo email address: ; read emailaddress ; export emailaddress
echo email password: ; read emailpassword ; export emailpassword

sed -i -e "s/smtpserver=.*/smtpserver=$smtpserver/" $parentdir/operations/variables
sed -i -e "s/emailaddress=.*/emailaddress=$emailaddress/" $parentdir/operations/variables
sed -i -e "s/emailpassword=.*/emailpassword=$emailpassword/" $parentdir/operations/variables

install () {
 if test -f "/etc/systemd/system/monitor.service" ; then
  $currentdir/function_remove_service
  $currentdir/function_install_postfix
  $currentdir/function_create_service
 else
  $currentdir/function_install_postfix
  $currentdir/function_create_service
 fi
}

install