#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
currentdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo =============================================================================================
echo - This will enable email alerts for cpu/disk/memory/temperature usage.
echo - You will be asked to provide the username and password of a gmail account.
echo - Before proceeding perform the following steps to enable access to any gmail account.
echo ---------------------------------------------------------------------------------------------
echo 1. Visit https://myaccount.google.com/lesssecureapps to enable less secure app access.
echo 2. Visit https://accounts.google.com/DisplayUnlockCaptcha to allow access to a gmail account.
echo =============================================================================================
read -p "press enter to continue"

echo gmail address: ; read emailaddress ; export emailaddress
echo gmail password: ; read emailpassword ; export emailpassword

sed -i -e "s/emailaddress=.*/emailaddress=$emailaddress/" $parentdir/operations/variables
sed -i -e "s/emailpassword=.*/emailpassword=$emailpassword/" $parentdir/operations/variables

install () {
 if test -f "/etc/systemd/system/monitor.service" ; then
  $currentdir/function_remove_service
  $currentdir/function_install_ssmtp
  $currentdir/function_create_service
 else
  $currentdir/function_install_ssmtp
  $currentdir/function_create_service
 fi
}

install