#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

service_youtube () {
sudo bash -c 'cat > /etc/systemd/system/youtube.service' << 'EOL'
[Unit]
Description=youtube service
After=network.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/cvlc --no-osd --network-caching=2000 --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=$width --height=$height --loop $youtubeurl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_youtube