#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")
source "$parentdir/operations/variables"

service_video () {
sudo bash -c "cat > /etc/systemd/system/video.service" << EOL
[Unit]
Description=video service
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/bin/bash -c "xinit /usr/bin/cvlc --no-osd --no-qt-privacy-ask --fullscreen --no-embedded-video --no-autoscale --width=$width --height=$height $videourl"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_video