#!/bin/bash

# variables
parentdir=$(dirname "$(dirname "$(readlink -f -- "$0")")")

service_audio () {
sudo bash -c "cat > /etc/systemd/system/audio.service" << EOL
[Unit]
Description=audio service
After=network.target

[Service]
ExecStart=/bin/bash -c "mpg123 --shuffle $parentdir/media/audio/*"
Restart=always

[Install]
WantedBy=multi-user.target
EOL
}

service_audio